openapi: 3.0.3
info:
  title: Order Service API
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
  - url: "http://127.0.0.1:4010/"

paths:
  /organization/groups:
    $ref: "openapispecs/sample/rolemanagement.yml#/paths/~1organization~1groups"



  #tags Description Here
tags:
  #-----------------------------------------
  - name: organization
    description: lms
